### ISSUE TITLE
标注是不是有个错误？

### ISSUE THREAD

**Issue by knifecaojia** [BoXiaolei/MyTransformer_pytorch#1]
这图红圈里是不是有个标注错误
![image](https://github.com/BoXiaolei/MyTransformer_pytorch/assets/19563544/11b05706-8549-4eeb-8cdd-61e91ea58970)

**Comment by BoXiaolei** [comment]
没错吧？这不对应的右边的第一个Tensor么，长度是[2,5], 专门构建的不等长的数据模拟句子长短不一的情况
